### ISSUE TITLE
heatmap question

### ISSUE THREAD

**Issue by ghost** [jbkunst/r-posts#1]
the heatmap example: https://github.com/jbkunst/r-posts/tree/master/042-infectious-diseases-and-vaccines, has no state names on the y-axis as in the ggplot example, how do I add these?

**Comment by jbkunst** [comment]
Manually. `hc_yAxis(categories = vectorofnames)` ;)

**Comment by ghost** [comment]
:-)  I had tried that but it didn't work out well - somehow Alabama is skipped. In your original code I had to add a as.numeric conversion for count as it was read as characters somehow. 

Here is my code (I use data.table --> shorter, faster, transparent)  :

```
# read
setwd("~/Documents/highcharts")
df = fread("measles.csv") %>% setDF
names(df) <- tolower(names(df))

# preprocessing
d = setDT(df) %>%
  melt(id.var = c("year", "week"), variable.name = "state", value.name = "count")
dx = d[, .(count = sum(as.numeric(count), na.rm = T)), by = .(year, state)]
dx[, state_id := .GRP, by = state]

# get name vector
dx[, state := str_to_title(state)]
statevec = dx$state %>% unique

# clean up and parse
dx = dx[, .(year, state_id, count)]
setnames(dx, c("x", "y", "value"))
ds = list.parse3(dx)

# colors
n = 4
stops = data.frame(q = 0:n/n,
                   c = substring(viridis(n + 1), 0, 7)) %>%
  list.parse2()

# plot
highchart() %>%
  hc_chart(type = "heatmap") %>%
  hc_add_series(data = ds) %>%
  hc_colorAxis(stops = stops) %>%
  hc_yAxis(categories = statevec)
```

**Comment by jbkunst** [comment]
@carbonmetrics 

Sorry fot the **late**, my apologies. Hope you found `hchart`. Now it's easy to chart heatmaps:
- http://rpubs.com/jbkunst/highcharter-hchart-data-frames  (the heatmaps, almost at the end)
- http://jkunst.com/highcharter/hchart.html#matrix

**Comment by jbkunst** [comment]
I'll close the issue, if you have more questions we can talk ;)!
